// Supabase public browser configuration.
// Replace these placeholders with values from Supabase Project Settings > API.
window.BYTE_BATTLE_SUPABASE_URL = 'zvnxwvpdqqbntapnzymg';
window.BYTE_BATTLE_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2bnh3dnBkcXFibnRhcG56eW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxMjU1OTcsImV4cCI6MjEwMjcwMTU5N30.4b_2MksSSyOOFZoQMyKSZ6M6UI8mwfxIC0DWkzRi-K4';
